services:
  kafka:
    image: wurstmeister/kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_BROKER_ID: 0
      KAFKA_CREATE_TOPICS: "purchase-created:1:1,purchase-complete:1:1"
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181
  mongo:
    image: mongo
    ports:
      - 27017:27017